#myfirstyamlfile
name: jekyllparty
description: My First Jekyll Website

author:
  name: Emma Sherwood-Forbes
  email: emmasf@gmail.com
  github: emmasf
  twitter: sherwoodforbes
  
permalink: pretty
future: true #default
show_drafts:false #defalut
